mainProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortner.urls')),
]

shortner/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views
app_name = 'shortner'
urlpatterns = [
    path('', views.index, name="index"),
    path('link/<pk>', views.link, name="link"),
]

shortner/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
    url = models.CharField(max_length=10000)
    uuid = models.CharField(max_length=10)

    def __str__(self):
        return self.uuid

shortner/views.py
from django.db.models.fields import EmailField
from django.shortcuts import redirect, render
from .models import Url
import uuid
from django.http import HttpResponse
# Create your views here.
def index(request):
    diction = {}
    if request.method =='POST':
        newUrl = Url()
        newUrl.url = request.POST.get('link')
        newUrl.uuid = str(uuid.uuid4())[:7]
        newUrl.save()
        diction.update({'uuid':newUrl.uuid})
    return render(request, 'index.html', context=diction)

def link(request, pk):
    gotoLink = Url.objects.get(uuid=pk)
    return redirect(gotoLink.url)

templates/index.html
<head>
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    <style>
        *,
*::before,
*::after {
  box-sizing: border-box;
}

body,
section {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
}

body {
  min-height: 100vh;
  font-family: "Lato", sans-serif;
  line-height: 1.5;
  color: #111;
}

main {
  max-width: 720px;
  width: 100%;
  border: 2.5px solid #330867;
  border-radius: 2.5px;
  box-shadow: 0 10px 20px rgba(17, 17, 17, 0.125),
    0 5px 5px rgba(17, 17, 17, 0.25);
  background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%);
}

h1 {
  padding: 1rem;
  color: white;
}

input,
button {
  font-family: inherit;
  line-height: inherit;
  color: inherit;
  border: 0;
  padding: 1rem;
}

input {
  box-sizing: border-box;
  width: 100%;
}

.buttons {
  display: flex;
}

button {
  cursor: pointer;
  flex: 1;
  background-color: transparent;
  color: white;
  &:hover {
    background-color: rgba(255, 255, 255, 0.5);
  }
}

section {
  min-height: 120px;
  text-align: center;
  background-color: white;
}

    </style>
</head>
<main>
  <a href="{% url 'shortner:index' %}"><h1>URL Shortener</h1></a>
  <form method="POST" action=".">
  <input type="text" name="link" placeholder="Enter URL here" value="https://" required>
  {% csrf_token %}
  <div class="buttons">
    <button type="submit">Shorten</button>
  </div>
  </form>
  
    <section id="section">
      {% if uuid %}
        <a href="{% url 'shortner:link' pk=uuid %}">https://{{uuid}}</a>
      {% endif %}

    </section>
    
</main>

<!-- <script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/create',
      data:{
        link:$('#link').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
        $('h2').html("www.surls.ga/"+data)
      }
    });
  });
</script> -->